project_id = "supabase"

[api]
port = 55321

[db]
port = 55322

[studio]
port = 55323

[inbucket]
port = 55324

[analytics]
enabled = false
port = 55327

[functions.create-admin]
verify_jwt = false

[functions.analyze-aligner-photo]
verify_jwt = false

[functions.create-analysis-alerts]
verify_jwt = true

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.send-assignment-emails]
verify_jwt = false

[functions.reset-password]
verify_jwt = false
